dist: trusty
language: python
python:
  - "3.6"
sudo: required
env:
  matrix:
    - COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
addons:
  apt:
    packages:
      - g++-5
    sources: &sources
      - llvm-toolchain-trusty-4.0
      - ubuntu-toolchain-r-test
before_install:
  - version="$(wget -q -O - http://sourceforge.net/projects/opencvlibrary/files/opencv-unix | egrep -m1 -o '\"[0-9](\.[0-9]+)+' | cut -c2-)"
  - mkdir OpenCV
  - cd OpenCV
  - sudo apt-get -qq remove ffmpeg x264 libx264-dev
  - sudo apt-get -qq install libopencv-dev build-essential checkinstall cmake pkg-config yasm libjpeg-dev libjasper-dev libavcodec-dev libavformat-dev libswscale-dev libdc1394-22-dev libxine-dev libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev libv4l-dev python-dev python-numpy libtbb-dev libqt4-dev libgtk2.0-dev libfaac-dev libmp3lame-dev libopencore-amrnb-dev libopencore-amrwb-dev libtheora-dev libvorbis-dev libxvidcore-dev x264 v4l-utils cmake qt5-default checkinstall
  - wget -O OpenCV-$version.zip http://sourceforge.net/projects/opencvlibrary/files/opencv-unix/$version/opencv-"$version".zip/download
  - unzip OpenCV-$version.zip
  - cd opencv-$version
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D INSTALL_C_EXAMPLES=OFF -D INSTALL_PYTHON_EXAMPLES=OFF -D BUILD_EXAMPLES=OFF -D WITH_QT=OFF -D WITH_OPENGL=OFF ..
  - make -j2
  - sudo checkinstall -y
  - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
  - sudo ldconfig
  - cd ../../../
install:
  - pip install -U -r requirements.txt
  - pip install -U opencv-python robotpy-cscore
script: python robot/robot.py test
