language: python
python:
  - "3.6"
sudo: false
env:
  matrix:
    - COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
addons:
  apt:
    packages:
      - g++-5
    sources: &sources
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
install:
  - curl -sL https://github.com/opencv/opencv/archive/3.2.0.zip > opencv.zip
  - unzip opencv.zip
  - cd opencv-3.2.0

  - mkdir build install
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=RELEASE -DBUILD_SHARED_LIBS=OFF -D CMAKE_INSTALL_PREFIX=$(pwd)/../install -D WITH_FFMPEG=OFF -D WITH_IPP=OFF ..
  - make -j4
  - make install
  - cd ../../

  - pip install -U -r requirements.txt
  - pip install -U opencv-python robotpy-cscore
script: python robot/robot.py test